{
    "data": {
        "@version": "3.0",
        "@time": "2024-07-20 09:54:46",
        "@type": "post",
        "@filename": "b000000025.xml",
        "open_time": "0000-00-00",
        "close_time": "0000-00-00",
        "lang_name": "Big5",
        "board_id": "1001278677",
        "node": "000000025",
        "site": "1000110001",
        "pt": "2023-07-09 20:59:18",
        "poster": "06004870",
        "realname": "曾浚楷",
        "email": "kenneth61215@gmail.com",
        "homepage": null,
        "subject": "搶答107",
        "content": "<p>107. 若遞迴到某層就異常終止，要如何強制它繼續執行到下一層？</p>\r\n\r\n<p>答: 使用try, throw, catch來進行對異常狀態(exception)的處理，例:</p>\r\n\r\n<p>在處理除法的遞迴外包上try，並在程式出現異常時，throw出異常狀態 (如: 分母為0)，並且跳到try外面的catch中來對異常狀態進行處理</p>\r\n\r\n<p>並回復遞迴狀態(如: depth等參數)，以接續進行遞迴。</p>",
        "attach": null,
        "rcount": null,
        "rank": null,
        "hit": "7",
        "lang": "1"
    }
}